<?php
/**
 * Template Name: VAVA — About (AR / EN)
 * Template Post Type: page
 *
 * @package VAVA_Living
 */
defined( 'ABSPATH' ) || exit;

$page_id       = get_queried_object_id();
$lang          = vava_current_language();
$hero_image    = vava_about_image_url( absint( vava_about_shared_field( $page_id, '_vava_about_hero_image_id', 0 ) ), 'assets/images/about-hero.png' );
$story_image   = vava_about_optional_image_url( absint( vava_about_shared_field( $page_id, '_vava_about_story_image_id', 0 ) ) );
$why_image     = vava_about_image_url( absint( vava_about_shared_field( $page_id, '_vava_about_why_image_id', 0 ) ), 'assets/images/about-why-vava.png' );
$story_content = vava_about_story_content( $page_id, $lang );
$why_content   = vava_about_why_content( $page_id, $lang );
$feature_items = vava_about_fixed_items( $page_id, '_vava_about_feature_items', $lang, 4 );
$vision_items  = vava_about_fixed_items( $page_id, '_vava_about_vision_items', $lang, 3 );

$GLOBALS['vava_page_data_name'] = 'en' === $lang ? 'about-vava-en.html' : 'about-vava.html';
$GLOBALS['vava_active_nav']     = 'about';
get_header( 'page' );
?>
<main>
<span class="blob sage"></span><span class="blob cream"></span><span class="leaf-line vava-inline-about-vava-1"></span>
<section class="section about-hero-section" id="about-hero"><div class="container hero-grid about-hero-grid"><div class="hero-copy about-hero-copy"><div class="eyebrow"><?php echo esc_html( vava_about_field( $page_id, '_vava_about_hero_eyebrow', $lang ) ); ?></div><h1><?php echo esc_html( vava_about_field( $page_id, '_vava_about_hero_title', $lang ) ); ?></h1><div class="vava-richtext-content"><?php echo vava_richtext_output( vava_about_field( $page_id, '_vava_about_hero_lead', $lang ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div><div class="small about-hero-note vava-richtext-content"><?php echo vava_richtext_output( vava_about_field( $page_id, '_vava_about_hero_note', $lang ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div></div><div aria-label="VAVA visual" class="visual-card about-hero-visual vava-about-dynamic-hero" style="--vava-about-hero-image:url('<?php echo esc_url( $hero_image ); ?>')"></div></div></section>
<section class="section about-story-section" id="noura-story"><div class="about-editorial"><aside class="about-kicker"><div class="eyebrow"><?php echo esc_html( vava_about_field( $page_id, '_vava_about_story_eyebrow', $lang ) ); ?></div><h2><?php echo esc_html( vava_about_field( $page_id, '_vava_about_story_title', $lang ) ); ?></h2><div class="vava-richtext-content"><?php echo vava_richtext_output( vava_about_field( $page_id, '_vava_about_story_intro', $lang ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div><?php if ( '' !== $story_image ) : ?><div class="about-story-image" style="background-image:url('<?php echo esc_url( $story_image ); ?>')" role="img" aria-label="<?php echo esc_attr( vava_about_field( $page_id, '_vava_about_story_title', $lang ) ); ?>"></div><?php endif; ?></aside><div class="about-flow"><div class="about-single-text-card soft-line"><?php echo vava_richtext_output( $story_content ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div></div></div></section>
<section class="section about-why-section" id="why-vava"><div class="why-poem"><div class="why-copy"><div class="eyebrow"><?php echo esc_html( vava_about_field( $page_id, '_vava_about_why_eyebrow', $lang ) ); ?></div><h2><?php echo esc_html( vava_about_field( $page_id, '_vava_about_why_title', $lang ) ); ?></h2><div class="about-single-text-card soft-line"><?php echo vava_richtext_output( $why_content ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div></div><div aria-hidden="true" class="why-orb vava-about-dynamic-why" style="--vava-about-why-image:url('<?php echo esc_url( $why_image ); ?>')"></div></div></section>
<section class="section about-features-section" id="vava-features"><div class="container about-features-shell"><div class="open-text about-features-head"><span class="eyebrow"><?php echo esc_html( vava_about_field( $page_id, '_vava_about_features_eyebrow', $lang ) ); ?></span><h2><?php echo esc_html( vava_about_field( $page_id, '_vava_about_features_title', $lang ) ); ?></h2><div class="vava-richtext-content"><?php echo vava_richtext_output( vava_about_field( $page_id, '_vava_about_features_intro', $lang ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div></div><div class="about-feature-grid"><?php foreach ( $feature_items as $item ) : ?><article class="about-feature-card"><h3><?php echo esc_html( (string) ( $item['title'] ?? '' ) ); ?></h3><div class="vava-richtext-content"><?php echo vava_richtext_output( (string) ( $item['text'] ?? '' ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div></article><?php endforeach; ?></div></div></section>
<section class="section about-vision-section" id="vava-vision"><div class="vision-shell"><div class="eyebrow"><?php echo esc_html( vava_about_field( $page_id, '_vava_about_vision_eyebrow', $lang ) ); ?></div><h2><?php echo esc_html( vava_about_field( $page_id, '_vava_about_vision_title', $lang ) ); ?></h2><div class="vava-richtext-content"><?php echo vava_richtext_output( vava_about_field( $page_id, '_vava_about_vision_intro', $lang ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div><div class="vision-steps"><?php foreach ( $vision_items as $item ) : ?><article class="vision-step"><h3><?php echo esc_html( (string) ( $item['title'] ?? '' ) ); ?></h3><div class="vava-richtext-content"><?php echo vava_richtext_output( (string) ( $item['text'] ?? '' ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div></article><?php endforeach; ?></div><?php $dream = (string) vava_about_field( $page_id, '_vava_about_vision_dream', $lang ); if ( '' !== trim( $dream ) ) : ?><div class="vision-dream vava-richtext-content"><?php echo vava_richtext_output( $dream ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div><?php endif; ?></div></section>
<section class="section about-invite-section" id="about-invitation"><div class="invite-panel"><div class="eyebrow"><?php echo esc_html( vava_about_field( $page_id, '_vava_about_invite_eyebrow', $lang ) ); ?></div><h2><?php echo esc_html( vava_about_field( $page_id, '_vava_about_invite_title', $lang ) ); ?></h2><div class="vava-richtext-content"><?php echo vava_richtext_output( vava_about_field( $page_id, '_vava_about_invite_description', $lang ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div><div class="btn-row"><a class="btn primary" href="<?php echo esc_url( vava_about_button_url( $page_id, 1, $lang ) ); ?>"><?php echo esc_html( vava_about_field( $page_id, '_vava_about_invite_button_1_text', $lang ) ); ?></a><a class="btn secondary" href="<?php echo esc_url( vava_about_button_url( $page_id, 2, $lang ) ); ?>"><?php echo esc_html( vava_about_field( $page_id, '_vava_about_invite_button_2_text', $lang ) ); ?></a><a class="btn coral" href="<?php echo esc_url( vava_about_button_url( $page_id, 3, $lang ) ); ?>"><?php echo esc_html( vava_about_field( $page_id, '_vava_about_invite_button_3_text', $lang ) ); ?></a></div></div></section>
</main>
<?php get_footer( 'page' ); ?>
